# Spring Properties
spring:
  application:
     name: MOVIE-SERVICE

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port